apps/inventario/apps/estados/models.py
from base.contrib.models import BaseModelMixin, RelationShipAudit
from config.db import db
from flask_login import current_user


class EstadosProductos(db.Model, BaseModelMixin, RelationShipAudit):
    __tablename__ = 'estados_productos'
    id = db.Column(db.Integer, primary_key=True)
    nombre_estado = db.Column(db.String(70), nullable=False, unique=True)
    activo = db.Column(db.Boolean, default=True)
    product = db.relationship('Productos', backref='estados_productos', lazy='dynamic')

    def __repr__(self):
        return f'{str(self.id)}', self.nombre_estado

    def __init__(self, nombre_estado, activo=True):
        super(EstadosProductos, self).__init__()
        self.nombre_estado = nombre_estado
        self.activo = activo

    @classmethod
    def get_query_all(cls, pk=None):
        lista = []

        for item in cls.get_all():
            if pk is not None:
                cls.query.filter_by(id=pk)
                for i in cls.get_all():
                    tupla = (i.id, i.nombre_estado)
                    lista.append(tupla)
            tupla = (item.id, item.nombre_estado)
            lista.append(tupla)

        return lista

apps/inventario/apps/estados/forms.py
from flask_wtf import FlaskForm
import wtforms
from wtforms.validators import DataRequired, Length


class EstadosForm(FlaskForm):
    nombre_estado = wtforms.StringField(label="Nombre del estado", validators=[DataRequired(),Length(max=70)],
                                        render_kw={'class': 'form-control', 'autofocus': 'on', 'autocomplete': 'off',
                                                   'placeholder': 'Ingrese un nombre para el estado'})

    activo = wtforms.BooleanField(label="Activo", default=True)

apps/inventario/apps/estados/__init__.py
from flask import Blueprint

estados = Blueprint("estados", __name__, template_folder="templates",url_prefix='/estados')

from . import routes

apps/inventario/apps/estados/routes.py
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required

from apps.inventario.apps.estados import estados
from apps.inventario.apps.estados.forms import EstadosForm
from apps.inventario.apps.estados.models import EstadosProductos


@estados.route("/list")
@login_required
def list_estados():
    query = EstadosProductos.get_all()
    context = {'title': 'Estados',
               'title_card': 'Lista de estado',
               'estados': query}
    return render_template("estados/list.html", context=context, add_registro=url_for("estados.add_estados"))


@estados.route("/add", methods=['GET', 'POST'])
@login_required
def add_estados():
    form = EstadosForm()
    context = {'title': 'Agregar Estado',
               'title_card': 'Agregar Estados',
               'form': form}
    if request.method == 'POST':
        if form.validate_on_submit():
            nombre = form.nombre_estado.data
            activo = form.activo.data
            try:
                estado = EstadosProductos.query.filter_by(nombre_estado=nombre).first()
                if not estado:
                    estado = EstadosProductos(nombre_estado=nombre, activo=activo)
                    estado.save()
                    return redirect(url_for('estados.list_estados'))
                else:
                    flash("El nombre del estado ya existe")
            except Exception as e:
                flash(str(e))
    return render_template("estados/add.html", context=context)


@estados.route("/edit/<int:pk>", methods=['GET', 'POST'])
@login_required
def edit_estados(pk):
    estado = EstadosProductos.query.get_or_404(pk)
    form = EstadosForm(obj=estado)
    context = {'title': 'Agregar Estado',
               'title_card': 'Agregar Estados',
               'form': form}

    if request.method == 'POST':
        if form.validate_on_submit():
            try:

                query = EstadosProductos.query.filter_by(nombre_estado=form.nombre_estado.data).first()
                if not query:
                    form = form.populate_obj(obj=estado)
                    estado.save()
                    return redirect(url_for('estados.list_estados'))
                else:
                    flash("El nombre del estado ya existe")
            except Exception as e:
                flash(str(e))
    return render_template("estados/add.html", context=context)


@estados.route("/delete/<int:pk>", methods=['GET', 'POST'])
@login_required
def delete_estados(pk):
    message = "Al eliminar este registro, se eliminaran los datos dependientes de este"
    estados = EstadosProductos.query.get_or_404(pk)
    context = {'title': 'Eliminar estado',
               'title_card': 'Eliminar estado',
               'form': '',
               'obj': estados,
               'message': message}
    try:
        if request.method == 'POST':
            action = request.form.get("action", None)
            if action == "delete":
                estados.delete()
                return redirect(url_for('estados.list_estados'))
    except Exception as e:
        flash(str(e))
    return render_template("estados/delete.html", context=context)

apps/inventario/templates/estados/add.html
{% extends 'form_base.html' %}
{% from 'macros/render_form.html' import render_form %}
{% block form_content %}
    {{ render_form(context.form) }}
{% endblock %}

apps/inventario/templates/estados/delete.html
{% extends 'delete_base.html' %}

apps/inventario/templates/estados/list.html
{% extends 'list_base.html' %}

{% block columns %}
    <tr>
        <th>Opciones</th>
        <th>Nombre producto</th>
        <th>Estado</th>
    </tr>
{% endblock %}

{% block rows %}

    {% for estado in context.estados %}
        <tr>
            <td>
                <a href="{{ url_for('estados.edit_estados',pk=estado.id) }}" class="btn btn-sm btn-default"><i
                        style="color: #334a4b" class="fas fa-edit"></i></a>
                <a href="{{ url_for('estados.delete_estados',pk=estado.id) }}" class="btn btn-sm btn-default"><i
                        style="color: red" class="fas fa-trash-alt"></i></a>
            </td>
            <td>{{ estado.nombre_estado }}</td>
            <td>{{ estado.activo }}</td>
        </tr>
    {% endfor %}
{% endblock %}

{% block card_footer %}
    <a href="{{ add_registro }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Agregar</a>
    <a href="" class="btn btn-success"><i class="fas fa-sync-alt"></i> Actualizar</a>
{% endblock %}